name: Sync Docker Images

on:
  push:
    paths:
      - 'images.yaml'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Read image list
        id: imagelist
        run: |
          images=$(yq eval '.images[] | {name: .name, tag: .tag, aliyun: .aliyun, tencent: .tencent}' images.yaml -o=json)
          echo "::set-output name=images::$images"

      - name: Pull and tag images
        run: |
          images=${{ steps.imagelist.outputs.images }}
          for img in $images; do
            docker pull ${img.name}:${img.tag}
            [[ ! -z "${img.aliyun}" ]] && docker tag ${img.name}:${img.tag} registry.aliyuncs.com/${img.aliyun}
            [[ ! -z "${img.tencent}" ]] && docker tag ${img.name}:${img.tag} ccr.ccs.tencentyun.com/${img.tencent}
          done

      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Log in to Tencent Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}

      - name: Push images to Aliyun and Tencent
        run: |
          images=${{ steps.imagelist.outputs.images }}
          for img in $images; do
            [[ ! -z "${img.aliyun}" ]] && docker push registry.aliyuncs.com/${img.aliyun}
            [[ ! -z "${img.tencent}" ]] && docker push ccr.ccs.tencentyun.com/${img.tencent}
          done
