name: Sync Docker Images

on:
  push:
    paths:
      - 'images.yaml'
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install yq
        run: sudo snap install yq

      - name: Pull and tag images
        run: |
          yq eval '.images[] | .name + ":" + .tag + " " + (.aliyun // "") + " " + (.tencent // "")' images.yaml | while read name tag aliyun tencent; do
            docker pull $name

            if [ -n "$aliyun" ]; then
              docker tag $name registry.aliyuncs.com/$aliyun
            fi
            if [ -n "$tencent" ]; then
              docker tag $name ccr.ccs.tencentyun.com/$tencent
            fi
          done

      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Log in to Tencent Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}

      - name: Push images to Aliyun and Tencent
        run: |
          yq eval '.images[] | .name + ":" + .tag + " " + (.aliyun // "") + " " + (.tencent // "")' images.yaml | while read name tag aliyun tencent; do
            if [ -n "$aliyun" ]; then
              docker push registry.aliyuncs.com/$aliyun
            fi
            if [ -n "$tencent" ]; then
              docker push ccr.ccs.tencentyun.com/$tencent
            fi
          done
