name: Sync Docker Images

on:
  push:
    paths:
      - 'images.yaml'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install yq
        run: sudo snap install yq

      - name: Pull and tag images
        run: |
          while IFS= read -r line; do
            name=$(echo $line | yq eval '.name' -)
            tag=$(echo $line | yq eval '.tag' -)
            aliyun=$(echo $line | yq eval '.aliyun' -)
            tencent=$(echo $line | yq eval '.tencent' -)

            docker pull $name:$tag

            if [ "$aliyun" != "null" ]; then
              docker tag $name:$tag registry.aliyuncs.com/$aliyun
            fi
            if [ "$tencent" != "null" ]; then
              docker tag $name:$tag ccr.ccs.tencentyun.com/$tencent
            fi
          done < <(yq eval '.images[] | tostring' images.yaml)

      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Log in to Tencent Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}

      - name: Push images to Aliyun and Tencent
        run: |
          while IFS= read -r line; do
            name=$(echo $line | yq eval '.name' -)
            tag=$(echo $line | yq eval '.tag' -)
            aliyun=$(echo $line | yq eval '.aliyun' -)
            tencent=$(echo $line | yq eval '.tencent' -)

            if [ "$aliyun" != "null" ]; then
              docker push registry.aliyuncs.com/$aliyun
            fi
            if [ "$tencent" != "null" ]; then
              docker push ccr.ccs.tencentyun.com/$tencent
            fi
          done < <(yq eval '.images[] | tostring' images.yaml)
